import type { Passage, Pool, Round } from "@/types";
import { apiFetch } from "@/lib/api/client";

// Pools and passages are bulk-generated by the tournament optimizer (see
// lib/services/tournamentOptimizer.ts, which posts the whole computed
// result to POST /api/rounds) — there's no individual create/delete route
// for either, only reads here plus the one real per-passage update
// (schedule fields).

export function getPools(): Promise<Pool[]> {
  return apiFetch<Pool[]>("/pools");
}

export function getPoolsByRound(round: Round): Promise<Pool[]> {
  return apiFetch<Pool[]>("/pools", { params: { round } });
}

export function getPassages(): Promise<Passage[]> {
  return apiFetch<Passage[]>("/passages");
}

// No single-item route exists on the backend (only the filtered list) —
// fetch and filter client-side.
export async function getPassageById(id: string): Promise<Passage | undefined> {
  const all = await getPassages();
  return all.find(p => p.id === id);
}

export function getPassagesByPool(poolId: string): Promise<Passage[]> {
  return apiFetch<Passage[]>("/passages", { params: { poolId } });
}

export async function getPassagesByTeam(teamId: string): Promise<Passage[]> {
  const all = await getPassages();
  return all.filter(p =>
    p.defenderTeamId === teamId ||
    p.opponentTeamId === teamId ||
    p.reporterTeamId === teamId ||
    p.extraTeamId    === teamId
  );
}

// Admin-only passage update — covers both everyday scheduling edits
// (day/timeSlot/room) and manual lineup corrections (problem number, role
// assignments), the only individual passage mutation the backend exposes
// (see backend/src/routes/passages.ts). Bulk generation still only goes
// through saveGeneratedRounds below.
export function updatePassage(
  id: string,
  patch: Partial<Pick<Passage,
    "day" | "timeSlot" | "room" | "problemNumber" |
    "defenderTeamId" | "opponentTeamId" | "reporterTeamId"
  >> & { extraTeamId?: string | null },
): Promise<Passage> {
  return apiFetch<Passage>(`/passages/${id}`, { method: "PUT", body: patch });
}

// ─── Bulk round generation (admin-only) ────────────────────────────────
// The tournament optimizer computes both rounds' pools/passages/pool-
// assignments and the constraint report entirely in memory, then hands
// the whole thing to this one call — the backend wipes round 2, then
// round 1, then writes everything new in a single transaction (see
// backend/src/routes/rounds.ts). There's no incremental create/update
// for generated pools or passages, only this full replace.
export interface GeneratedRoundPayload {
  pools: Pool[];
  passages: Passage[];
  teamPoolAssignments: { teamId: string; poolId: string }[];
}

export function saveGeneratedRounds(payload: {
  round1: GeneratedRoundPayload;
  round2: GeneratedRoundPayload;
  report: { generatedAt: string; totalScore: number; violations: unknown[] };
}): Promise<void> {
  return apiFetch<void>("/rounds", { method: "POST", body: payload });
}

// Wipes just one round (its pools + passages + the teams' pool references)
// without regenerating anything.
export function deleteRound(round: Round): Promise<void> {
  return apiFetch<void>(`/rounds/${round}`, { method: "DELETE" });
}
